version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: post-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
    - '5432:5432'
    volumes:
    - ./data:/var/lib/postgresql/data
