version: '3.8'

services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-container
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      ORACLE_ALLOW_REMOTE: "true"  # Zezwól na zdalne połączenia
    volumes:
      - oracle_data:/u01/app/oracle/oradata  # Trwałe dane bazy

volumes:
  oracle_data:
